Saper: app::managers::SettingsInteractor Class Reference
app::managers::SettingsInteractor Class Reference
QML-интерактор настроек приложения.
#include <settings_interactor.h>
Public Member Functions
SettingsInteractor (QObject *parent=nullptr)
Множитель масштаба GUI.
void OnUpdateInteractor () override
Отправляет сигналы изменения всех свойств.
void setGuiMultiply (qint32 value)
Задаёт множитель масштаба GUI.
void setMusicVolume (qint32 value)
Задаёт громкость музыки.
void setSoundVolume (qint32 value)
Задаёт громкость звуковых эффектов.
void setAudioVolume (qint32 value)
Задаёт общую громкость аудио.
void setSettingsFile (QFileSPtr file)
Задаёт файл настроек.
qint32 guiMultiply () const
qint32 musicVolume () const
qint32 soundVolume () const
qint32 audioVolume () const
QFileSPtr settingsFile () const
void SetUpdateFileCall (std::function< void()> updateFileCall)
Задаёт callback сохранения настроек.
void guiMultiplyChanged ()
Сигнал изменения guiMultiply.
void musicVolumeChanged ()
Сигнал изменения musicVolume.
void soundVolumeChanged ()
Сигнал изменения soundVolume.
void audioVolumeChanged ()
Сигнал изменения audioVolume.
Detailed Description
QML-интерактор настроек приложения.
Хранит настройки интерфейса и звука, предоставляет их как Q_PROPERTY и вызывает callback сохранения при изменении значений. Числовые значения ограничиваются диапазоном от 0 до 100.
Definition at line 25 of file settings_interactor.h.
Constructor & Destructor Documentation
SettingsInteractor()
app::managers::SettingsInteractor::SettingsInteractor (QObject * parent = nullptr)
Множитель масштаба GUI.
Громкость музыки.
Громкость звуковых эффектов.
Общая громкость аудио.
Создаёт интерактор настроек.
Definition at line 9 of file settings_interactor.cpp.
Member Function Documentation
audioVolume()
qint32 app::managers::SettingsInteractor::audioVolume () const
Returns
Общая громкость аудио.
Definition at line 64 of file settings_interactor.cpp.
audioVolumeChanged()
void app::managers::SettingsInteractor::audioVolumeChanged ()
Сигнал изменения audioVolume.
Referenced by OnUpdateInteractor(), and setAudioVolume().
guiMultiply()
qint32 app::managers::SettingsInteractor::guiMultiply () const
Returns
Множитель масштаба GUI.
Definition at line 52 of file settings_interactor.cpp.
guiMultiplyChanged()
void app::managers::SettingsInteractor::guiMultiplyChanged ()
Сигнал изменения guiMultiply.
Referenced by OnUpdateInteractor(), and setGuiMultiply().
musicVolume()
qint32 app::managers::SettingsInteractor::musicVolume () const
Returns
Громкость музыки.
Definition at line 56 of file settings_interactor.cpp.
musicVolumeChanged()
void app::managers::SettingsInteractor::musicVolumeChanged ()
Сигнал изменения musicVolume.
Referenced by OnUpdateInteractor(), and setMusicVolume().
OnUpdateInteractor()
void app::managers::SettingsInteractor::OnUpdateInteractor () override virtual
Отправляет сигналы изменения всех свойств.
Implements app::managers::IUpdateInteractor.
Definition at line 11 of file settings_interactor.cpp.
References audioVolumeChanged(), guiMultiplyChanged(), musicVolumeChanged(), and soundVolumeChanged().
setAudioVolume()
void app::managers::SettingsInteractor::setAudioVolume (qint32 value)
Задаёт общую громкость аудио.
Definition at line 37 of file settings_interactor.cpp.
References audioVolumeChanged(), and utility::ValueRange().
setGuiMultiply()
void app::managers::SettingsInteractor::setGuiMultiply (qint32 value)
Задаёт множитель масштаба GUI.
Definition at line 19 of file settings_interactor.cpp.
References guiMultiplyChanged(), and utility::ValueRange().
setMusicVolume()
void app::managers::SettingsInteractor::setMusicVolume (qint32 value)
Задаёт громкость музыки.
Definition at line 25 of file settings_interactor.cpp.
References musicVolumeChanged(), and utility::ValueRange().
setSettingsFile()
void app::managers::SettingsInteractor::setSettingsFile (QFileSPtr file)
Задаёт файл настроек.
Definition at line 43 of file settings_interactor.cpp.
setSoundVolume()
void app::managers::SettingsInteractor::setSoundVolume (qint32 value)
Задаёт громкость звуковых эффектов.
Definition at line 31 of file settings_interactor.cpp.
References soundVolumeChanged(), and utility::ValueRange().
settingsFile()
QFileSPtr app::managers::SettingsInteractor::settingsFile () const
Returns
Файл настроек.
Definition at line 68 of file settings_interactor.cpp.
SetUpdateFileCall()
void app::managers::SettingsInteractor::SetUpdateFileCall (std::function< void()> updateFileCall)
Задаёт callback сохранения настроек.
Parameters
updateFileCall Функция, вызываемая после изменения настройки.
Definition at line 47 of file settings_interactor.cpp.
soundVolume()
qint32 app::managers::SettingsInteractor::soundVolume () const
Returns
Громкость звуковых эффектов.
Definition at line 60 of file settings_interactor.cpp.
soundVolumeChanged()
void app::managers::SettingsInteractor::soundVolumeChanged ()
Сигнал изменения soundVolume.
Referenced by OnUpdateInteractor(), and setSoundVolume().
The documentation for this class was generated from the following files:
app/managers/settings_manager/settings_interactor.h
app/managers/settings_manager/settings_interactor.cpp