Saper: app::managers::TextureInteractor Class Reference
app::managers::TextureInteractor Class Reference
QML-интерактор путей к текстурам UI.
#include <texture_interactor.h>
Public Member Functions
TextureInteractor (QObject *obj=nullptr)
Фоновая текстура.
void OnUpdateInteractor () override
Отправляет сигналы изменения всех текстурных свойств.
void bg01Changed ()
void buttonLeftChanged ()
void buttonPlashChanged ()
void buttonRightChanged ()
void leftButtonChanged ()
void leftSliderBorderChanged ()
void logoChanged ()
void rightButtonChanged ()
void rightSliderBorderChanged ()
void selectedCheckboxChanged ()
void selectedCornerChanged ()
void selectedProfileChanged ()
void sliderChanged ()
void sliderPlashChanged ()
void unselectedButtonLeftBorderChanged ()
void unselectedButtonPlashChanged ()
void unselectedButtonRightBorderChanged ()
void unselectedCheckboxChanged ()
void unselectedCornerChanged ()
void unselectedProfileChanged ()
Public Attributes
QString m_bg01
QString m_buttonLeft
QString m_buttonPlash
QString m_buttonRight
QString m_leftButton
QString m_leftSliderBorder
QString m_logo
QString m_rightButton
QString m_rightSliderBorder
QString m_selectedCheckbox
QString m_selectedCorner
QString m_selectedProfile
QString m_slider
QString m_sliderPlash
QString m_unselectedButtonLeftBorder
QString m_unselectedButtonPlash
QString m_unselectedButtonRightBorder
QString m_unselectedCheckbox
QString m_unselectedCorner
QString m_unselectedProfile
Detailed Description
QML-интерактор путей к текстурам UI.
ResourceManager заполняет свойства объекта путями к файлам выбранного ресурсного набора. QML использует эти свойства как источники изображений.
Definition at line 19 of file texture_interactor.h.
Constructor & Destructor Documentation
TextureInteractor()
app::managers::TextureInteractor::TextureInteractor (QObject * obj = nullptr)
Фоновая текстура.
Левая часть кнопки.
Центральная часть кнопки.
Правая часть кнопки.
Текстура кнопки направления влево.
Левая граница слайдера.
Логотип приложения.
Текстура кнопки направления вправо.
Правая граница слайдера.
Выбранный checkbox.
Выбранный угол/рамка UI.
Выбранный профиль.
Текстура ползунка.
Центральная часть слайдера.
Левая граница невыбранной кнопки.
Центральная часть невыбранной кнопки.
Правая граница невыбранной кнопки.
Невыбранный checkbox.
Невыбранный угол/рамка UI.
Невыбранный профиль.
Создаёт интерактор текстур.
Definition at line 6 of file texture_interactor.cpp.
Member Function Documentation
bg01Changed()
void app::managers::TextureInteractor::bg01Changed ()
Referenced by OnUpdateInteractor().
buttonLeftChanged()
void app::managers::TextureInteractor::buttonLeftChanged ()
Referenced by OnUpdateInteractor().
buttonPlashChanged()
void app::managers::TextureInteractor::buttonPlashChanged ()
Referenced by OnUpdateInteractor().
buttonRightChanged()
void app::managers::TextureInteractor::buttonRightChanged ()
Referenced by OnUpdateInteractor().
leftButtonChanged()
void app::managers::TextureInteractor::leftButtonChanged ()
Referenced by OnUpdateInteractor().
leftSliderBorderChanged()
void app::managers::TextureInteractor::leftSliderBorderChanged ()
Referenced by OnUpdateInteractor().
logoChanged()
void app::managers::TextureInteractor::logoChanged ()
Referenced by OnUpdateInteractor().
OnUpdateInteractor()
void app::managers::TextureInteractor::OnUpdateInteractor () override virtual
Отправляет сигналы изменения всех текстурных свойств.
Implements app::managers::IUpdateInteractor.
Definition at line 8 of file texture_interactor.cpp.
References bg01Changed(), buttonLeftChanged(), buttonPlashChanged(), buttonRightChanged(), leftButtonChanged(), leftSliderBorderChanged(), logoChanged(), rightButtonChanged(), rightSliderBorderChanged(), selectedCheckboxChanged(), selectedCornerChanged(), selectedProfileChanged(), sliderChanged(), sliderPlashChanged(), unselectedButtonLeftBorderChanged(), unselectedButtonPlashChanged(), unselectedButtonRightBorderChanged(), unselectedCheckboxChanged(), unselectedCornerChanged(), and unselectedProfileChanged().
rightButtonChanged()
void app::managers::TextureInteractor::rightButtonChanged ()
Referenced by OnUpdateInteractor().
rightSliderBorderChanged()
void app::managers::TextureInteractor::rightSliderBorderChanged ()
Referenced by OnUpdateInteractor().
selectedCheckboxChanged()
void app::managers::TextureInteractor::selectedCheckboxChanged ()
Referenced by OnUpdateInteractor().
selectedCornerChanged()
void app::managers::TextureInteractor::selectedCornerChanged ()
Referenced by OnUpdateInteractor().
selectedProfileChanged()
void app::managers::TextureInteractor::selectedProfileChanged ()
Referenced by OnUpdateInteractor().
sliderChanged()
void app::managers::TextureInteractor::sliderChanged ()
Referenced by OnUpdateInteractor().
sliderPlashChanged()
void app::managers::TextureInteractor::sliderPlashChanged ()
Referenced by OnUpdateInteractor().
unselectedButtonLeftBorderChanged()
void app::managers::TextureInteractor::unselectedButtonLeftBorderChanged ()
Referenced by OnUpdateInteractor().
unselectedButtonPlashChanged()
void app::managers::TextureInteractor::unselectedButtonPlashChanged ()
Referenced by OnUpdateInteractor().
unselectedButtonRightBorderChanged()
void app::managers::TextureInteractor::unselectedButtonRightBorderChanged ()
Referenced by OnUpdateInteractor().
unselectedCheckboxChanged()
void app::managers::TextureInteractor::unselectedCheckboxChanged ()
Referenced by OnUpdateInteractor().
unselectedCornerChanged()
void app::managers::TextureInteractor::unselectedCornerChanged ()
Referenced by OnUpdateInteractor().
unselectedProfileChanged()
void app::managers::TextureInteractor::unselectedProfileChanged ()
Referenced by OnUpdateInteractor().
Member Data Documentation
m_bg01
QString app::managers::TextureInteractor::m_bg01
Definition at line 95 of file texture_interactor.h.
m_buttonLeft
QString app::managers::TextureInteractor::m_buttonLeft
Definition at line 96 of file texture_interactor.h.
m_buttonPlash
QString app::managers::TextureInteractor::m_buttonPlash
Definition at line 97 of file texture_interactor.h.
m_buttonRight
QString app::managers::TextureInteractor::m_buttonRight
Definition at line 98 of file texture_interactor.h.
m_leftButton
QString app::managers::TextureInteractor::m_leftButton
Definition at line 99 of file texture_interactor.h.
m_leftSliderBorder
QString app::managers::TextureInteractor::m_leftSliderBorder
Definition at line 100 of file texture_interactor.h.
m_logo
QString app::managers::TextureInteractor::m_logo
Definition at line 101 of file texture_interactor.h.
m_rightButton
QString app::managers::TextureInteractor::m_rightButton
Definition at line 102 of file texture_interactor.h.
m_rightSliderBorder
QString app::managers::TextureInteractor::m_rightSliderBorder
Definition at line 103 of file texture_interactor.h.
m_selectedCheckbox
QString app::managers::TextureInteractor::m_selectedCheckbox
Definition at line 104 of file texture_interactor.h.
m_selectedCorner
QString app::managers::TextureInteractor::m_selectedCorner
Definition at line 105 of file texture_interactor.h.
m_selectedProfile
QString app::managers::TextureInteractor::m_selectedProfile
Definition at line 106 of file texture_interactor.h.
m_slider
QString app::managers::TextureInteractor::m_slider
Definition at line 107 of file texture_interactor.h.
m_sliderPlash
QString app::managers::TextureInteractor::m_sliderPlash
Definition at line 108 of file texture_interactor.h.
m_unselectedButtonLeftBorder
QString app::managers::TextureInteractor::m_unselectedButtonLeftBorder
Definition at line 109 of file texture_interactor.h.
m_unselectedButtonPlash
QString app::managers::TextureInteractor::m_unselectedButtonPlash
Definition at line 110 of file texture_interactor.h.
m_unselectedButtonRightBorder
QString app::managers::TextureInteractor::m_unselectedButtonRightBorder
Definition at line 111 of file texture_interactor.h.
m_unselectedCheckbox
QString app::managers::TextureInteractor::m_unselectedCheckbox
Definition at line 112 of file texture_interactor.h.
m_unselectedCorner
QString app::managers::TextureInteractor::m_unselectedCorner
Definition at line 113 of file texture_interactor.h.
m_unselectedProfile
QString app::managers::TextureInteractor::m_unselectedProfile
Definition at line 114 of file texture_interactor.h.
The documentation for this class was generated from the following files:
app/managers/texture_manager/texture_interactor.h
app/managers/texture_manager/texture_interactor.cpp