Saper: core::MinefieldStorage Class Reference
core::MinefieldStorage Class Reference
Линейное хранилище клеток минного поля.
#include <minefield_storage.h>
Public Types
using Storage = std::vector<Field>
Контейнер клеток поля.
Public Member Functions
MinefieldStorage (MinefieldInteractorSPtr minefieldInteractor)
Создаёт хранилище для заданных параметров поля.
void Reset ()
Пересоздаёт контейнер под текущий размер поля и сбрасывает клетки.
bool IsValid (Pos x, Pos y) const
Проверяет, попадает ли координата внутрь поля.
std::size_t Size () const
std::size_t Index (Pos x, Pos y) const
Преобразует координаты клетки в линейный индекс.
Field & At (Pos x, Pos y)
Возвращает клетку по координатам.
Field & At (std::size_t index)
Возвращает клетку по линейному индексу.
template<typename Func>
void ForEachNeighbour (std::size_t index, Func &&fn)
Вызывает обработчик для каждой валидной соседней клетки.
Static Public Attributes
static const Pos NeighbourCount = 8
Максимальное количество соседей у клетки.
Detailed Description
Линейное хранилище клеток минного поля.
Класс отвечает за хранение Field, преобразование координат в линейные индексы, проверку границ и обход соседей. Размер поля берётся из MinefieldInteractor.
Definition at line 25 of file minefield_storage.h.
Member Typedef Documentation
Storage
using core::MinefieldStorage::Storage = std::vector<Field>
Контейнер клеток поля.
Definition at line 29 of file minefield_storage.h.
Constructor & Destructor Documentation
MinefieldStorage()
core::MinefieldStorage::MinefieldStorage (MinefieldInteractorSPtr minefieldInteractor)
Создаёт хранилище для заданных параметров поля.
Parameters
minefieldInteractor Параметры поля.
Definition at line 6 of file minefield_storage.cpp.
Member Function Documentation
At() [1/2]
Field & core::MinefieldStorage::At (Pos x, Pos y)
Возвращает клетку по координатам.
Precondition
Координата должна быть валидной.
Definition at line 36 of file minefield_storage.cpp.
References Index().
Referenced by ForEachNeighbour().
At() [2/2]
Field & core::MinefieldStorage::At (std::size_t index)
Возвращает клетку по линейному индексу.
Precondition
index должен быть меньше Size().
Definition at line 41 of file minefield_storage.cpp.
ForEachNeighbour()
template<typename Func> void core::MinefieldStorage::ForEachNeighbour (std::size_t index, Func && fn) inline
Вызывает обработчик для каждой валидной соседней клетки.
Обработчик вызывается в виде fn(index, field), где index — линейный индекс соседа, а field — ссылка на соседнюю клетку.
Template Parameters
Func Тип вызываемого объекта.
Parameters
index Индекс клетки, соседей которой нужно обойти.
fn Обработчик соседней клетки.
Definition at line 88 of file minefield_storage.h.
References At(), Index(), IsValid(), and NeighbourCount.
Index()
std::size_t core::MinefieldStorage::Index (Pos x, Pos y) const
Преобразует координаты клетки в линейный индекс.
Parameters
x Горизонтальная координата клетки.
y Вертикальная координата клетки.
Returns
Индекс клетки в Storage.
Precondition
Координата должна быть валидной.
Definition at line 31 of file minefield_storage.cpp.
Referenced by At(), and ForEachNeighbour().
IsValid()
bool core::MinefieldStorage::IsValid (Pos x, Pos y) const
Проверяет, попадает ли координата внутрь поля.
Parameters
x Горизонтальная координата клетки.
y Вертикальная координата клетки.
Returns
true, если координата валидна.
Definition at line 18 of file minefield_storage.cpp.
Referenced by ForEachNeighbour().
Reset()
void core::MinefieldStorage::Reset ()
Пересоздаёт контейнер под текущий размер поля и сбрасывает клетки.
Definition at line 9 of file minefield_storage.cpp.
References Size().
Size()
std::size_t core::MinefieldStorage::Size () const
Returns
Общее количество клеток.
Definition at line 26 of file minefield_storage.cpp.
Referenced by Reset().
Member Data Documentation
NeighbourCount
const Pos core::MinefieldStorage::NeighbourCount = 8 static
Максимальное количество соседей у клетки.
Definition at line 32 of file minefield_storage.h.
Referenced by ForEachNeighbour().
The documentation for this class was generated from the following files:
core/game/minefield_storage.h
core/game/minefield_storage.cpp