Saper: core::MinefieldModel Class Reference
core::MinefieldModel Class Reference
Qt-модель минного поля для отображения в QML.
#include <minefield_model.h>
Public Types
enum class Role {
X = Qt::UserRole + 1 , Y , IsOpen , IsFlagged ,
Value , TextureIndex
}
Горизонтальное смещение камеры в координатах доски.
Public Member Functions
MinefieldModel (MinefieldInteractorSPtr minefiledInteractorSPtr, MinefieldStorageSPtr minefieldStorageSPtr, app::managers::GameInteractorSPtr gameInteractorSPtr, app::managers::SettingsInteractorSPtr settingsInteractorSPtr, QObject *parent=nullptr)
Создаёт модель минного поля.
QModelIndex index (int row, int column, const QModelIndex &parent={}) const override
QModelIndex parent (const QModelIndex &index) const override
int rowCount (const QModelIndex &parent={}) const override
int columnCount (const QModelIndex &parent={}) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QHash< int, QByteArray > roleNames () const override
void setCameraX (qreal value)
Задаёт горизонтальное смещение камеры.
void setCameraY (qreal value)
Задаёт вертикальное смещение камеры.
void setViewportWidth (qreal value)
Задаёт ширину видимой области.
void setViewportHeight (qreal value)
Задаёт высоту видимой области.
void setEdgeWidth (qreal value)
Задаёт горизонтальный размер рамки доски.
void setEdgeHeight (qreal value)
Задаёт вертикальный размер рамки доски.
qreal cameraX () const
qreal cameraY () const
qreal cellSize () const
qreal viewportWidth () const
qreal viewportHeight () const
qreal edgeWidth () const
qreal edgeHeight () const
qreal boardWidth () const
qreal boardHeight () const
qreal minefieldHeight () const
qreal minefieldWidth () const
void RefreshModel ()
Уведомляет представление об изменении всех клеток модели.
void leftClickAt (qreal mouseX, qreal mouseY)
Обрабатывает левый клик по viewport.
void rightClickAt (qreal mouseX, qreal mouseY)
Обрабатывает правый клик по viewport.
void moveCameraBy (qreal dx, qreal dy)
Сдвигает камеру на заданное смещение.
void clampCamera ()
Принудительно ограничивает камеру границами доски.
void cameraXChanged ()
Сигнал изменения cameraX.
void cameraYChanged ()
Сигнал изменения cameraY.
void fieldGeometryChanged ()
Сигнал изменения размеров поля, доски или viewport.
Static Public Attributes
static constexpr const qreal CellSize = 5.0
Базовый размер клетки до применения масштаба GUI.
Detailed Description
Qt-модель минного поля для отображения в QML.
Каждая строка модели соответствует одной клетке поля. Модель отдаёт роли для QML-делегатов, обрабатывает клики в координатах viewport и хранит параметры камеры, позволяющие перемещаться по доске большого размера.
Definition at line 26 of file minefield_model.h.
Member Enumeration Documentation
Role
enum class core::MinefieldModel::Role strong
Горизонтальное смещение камеры в координатах доски.
Вертикальное смещение камеры в координатах доски.
Размер клетки с учётом текущего масштаба GUI.
Ширина видимой области.
Высота видимой области.
Горизонтальный размер рамки доски.
Вертикальный размер рамки доски.
Полная ширина доски вместе с рамкой.
Полная высота доски вместе с рамкой.
Высота игрового поля без рамки.
Ширина игрового поля без рамки.
Роли модели, доступные из QML.
Enumerator
X
Горизонтальная координата клетки.
Y
Вертикальная координата клетки.
IsOpen
Открыта ли клетка.
IsFlagged
Есть ли на клетке флаг.
Value
Отображаемое значение клетки.
TextureIndex
Индекс текстуры клетки.
Definition at line 57 of file minefield_model.h.
Constructor & Destructor Documentation
MinefieldModel()
core::MinefieldModel::MinefieldModel (MinefieldInteractorSPtr minefiledInteractorSPtr, MinefieldStorageSPtr minefieldStorageSPtr, app::managers::GameInteractorSPtr gameInteractorSPtr, app::managers::SettingsInteractorSPtr settingsInteractorSPtr, QObject * parent = nullptr) explicit
Создаёт модель минного поля.
Parameters
minefiledInteractorSPtr Параметры поля.
minefieldStorageSPtr Хранилище клеток.
gameInteractorSPtr Обработчик игровых действий.
settingsInteractorSPtr Настройки приложения.
parent Родительский QObject.
Definition at line 20 of file minefield_model.cpp.
References parent().
Member Function Documentation
boardHeight()
qreal core::MinefieldModel::boardHeight () const
Returns
Высота доски вместе с рамкой.
Definition at line 207 of file minefield_model.cpp.
References minefieldHeight().
boardWidth()
qreal core::MinefieldModel::boardWidth () const
Returns
Ширина доски вместе с рамкой.
Definition at line 202 of file minefield_model.cpp.
References minefieldWidth().
cameraX()
qreal core::MinefieldModel::cameraX () const
Returns
Горизонтальное смещение камеры.
Definition at line 167 of file minefield_model.cpp.
cameraXChanged()
void core::MinefieldModel::cameraXChanged ()
Сигнал изменения cameraX.
Referenced by clampCamera(), and setCameraX().
cameraY()
qreal core::MinefieldModel::cameraY () const
Returns
Вертикальное смещение камеры.
Definition at line 172 of file minefield_model.cpp.
cameraYChanged()
void core::MinefieldModel::cameraYChanged ()
Сигнал изменения cameraY.
Referenced by clampCamera(), and setCameraY().
cellSize()
qreal core::MinefieldModel::cellSize () const
Returns
Размер клетки с учётом масштаба GUI.
Definition at line 177 of file minefield_model.cpp.
References CellSize.
Referenced by minefieldHeight(), and minefieldWidth().
clampCamera()
void core::MinefieldModel::clampCamera ()
Принудительно ограничивает камеру границами доски.
Definition at line 250 of file minefield_model.cpp.
References cameraXChanged(), and cameraYChanged().
columnCount()
int core::MinefieldModel::columnCount (const QModelIndex & parent = {}) const override
Definition at line 51 of file minefield_model.cpp.
References parent().
data()
QVariant core::MinefieldModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 56 of file minefield_model.cpp.
References index(), IsFlagged, IsOpen, rowCount(), TextureIndex, Value, X, and Y.
edgeHeight()
qreal core::MinefieldModel::edgeHeight () const
Returns
Вертикальный размер рамки доски.
Definition at line 197 of file minefield_model.cpp.
edgeWidth()
qreal core::MinefieldModel::edgeWidth () const
Returns
Горизонтальный размер рамки доски.
Definition at line 192 of file minefield_model.cpp.
fieldGeometryChanged()
void core::MinefieldModel::fieldGeometryChanged ()
Сигнал изменения размеров поля, доски или viewport.
Referenced by setEdgeHeight(), setEdgeWidth(), setViewportHeight(), and setViewportWidth().
index()
QModelIndex core::MinefieldModel::index (int row, int column, const QModelIndex & parent = {}) const override
Definition at line 31 of file minefield_model.cpp.
References parent().
Referenced by data(), parent(), and RefreshModel().
leftClickAt()
void core::MinefieldModel::leftClickAt (qreal mouseX, qreal mouseY)
Обрабатывает левый клик по viewport.
Parameters
mouseX X-координата клика относительно видимой области.
mouseY Y-координата клика относительно видимой области.
Definition at line 227 of file minefield_model.cpp.
minefieldHeight()
qreal core::MinefieldModel::minefieldHeight () const
Returns
Высота игрового поля без рамки.
Definition at line 217 of file minefield_model.cpp.
References cellSize().
Referenced by boardHeight().
minefieldWidth()
qreal core::MinefieldModel::minefieldWidth () const
Returns
Ширина игрового поля без рамки.
Definition at line 212 of file minefield_model.cpp.
References cellSize().
Referenced by boardWidth().
moveCameraBy()
void core::MinefieldModel::moveCameraBy (qreal dx, qreal dy)
Сдвигает камеру на заданное смещение.
Parameters
dx Смещение по X.
dy Смещение по Y.
Definition at line 245 of file minefield_model.cpp.
parent()
QModelIndex core::MinefieldModel::parent (const QModelIndex & index) const override
Definition at line 36 of file minefield_model.cpp.
References index().
Referenced by columnCount(), index(), MinefieldModel(), and rowCount().
RefreshModel()
void core::MinefieldModel::RefreshModel ()
Уведомляет представление об изменении всех клеток модели.
Definition at line 222 of file minefield_model.cpp.
References index(), and rowCount().
rightClickAt()
void core::MinefieldModel::rightClickAt (qreal mouseX, qreal mouseY)
Обрабатывает правый клик по viewport.
Parameters
mouseX X-координата клика относительно видимой области.
mouseY Y-координата клика относительно видимой области.
Definition at line 236 of file minefield_model.cpp.
roleNames()
QHash< int, QByteArray > core::MinefieldModel::roleNames () const override
Definition at line 87 of file minefield_model.cpp.
References IsFlagged, IsOpen, TextureIndex, Value, X, and Y.
rowCount()
int core::MinefieldModel::rowCount (const QModelIndex & parent = {}) const override
Definition at line 41 of file minefield_model.cpp.
References parent().
Referenced by data(), and RefreshModel().
setCameraX()
void core::MinefieldModel::setCameraX (qreal value)
Задаёт горизонтальное смещение камеры.
Definition at line 99 of file minefield_model.cpp.
References cameraXChanged().
setCameraY()
void core::MinefieldModel::setCameraY (qreal value)
Задаёт вертикальное смещение камеры.
Definition at line 110 of file minefield_model.cpp.
References cameraYChanged().
setEdgeHeight()
void core::MinefieldModel::setEdgeHeight (qreal value)
Задаёт вертикальный размер рамки доски.
Definition at line 156 of file minefield_model.cpp.
References fieldGeometryChanged().
setEdgeWidth()
void core::MinefieldModel::setEdgeWidth (qreal value)
Задаёт горизонтальный размер рамки доски.
Definition at line 145 of file minefield_model.cpp.
References fieldGeometryChanged().
setViewportHeight()
void core::MinefieldModel::setViewportHeight (qreal value)
Задаёт высоту видимой области.
Definition at line 133 of file minefield_model.cpp.
References fieldGeometryChanged().
setViewportWidth()
void core::MinefieldModel::setViewportWidth (qreal value)
Задаёт ширину видимой области.
Definition at line 121 of file minefield_model.cpp.
References fieldGeometryChanged().
viewportHeight()
qreal core::MinefieldModel::viewportHeight () const
Returns
Высота видимой области.
Definition at line 187 of file minefield_model.cpp.
viewportWidth()
qreal core::MinefieldModel::viewportWidth () const
Returns
Ширина видимой области.
Definition at line 182 of file minefield_model.cpp.
Member Data Documentation
CellSize
const qreal core::MinefieldModel::CellSize = 5.0 static constexpr
Базовый размер клетки до применения масштаба GUI.
Definition at line 70 of file minefield_model.h.
Referenced by cellSize().
The documentation for this class was generated from the following files:
core/playground/minefield_model.h
core/playground/minefield_model.cpp